---
# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: gh-templates:.github/common-settings.yml

repository:
  name: "gh-templates"
  description: "GitHub Templates for Repositories."
  homepage: "https://rwxd.github.io/gh-templates/"
  topics: "github, templating"
